// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNYFFvl77qzVkuUxQLgVkEYATbRdzmfg',
    appId: '1:824650774430:web:f065502b1c344e7825488f',
    messagingSenderId: '824650774430',
    projectId: 'around-egypt-1cb7d',
    authDomain: 'around-egypt-1cb7d.firebaseapp.com',
    storageBucket: 'around-egypt-1cb7d.appspot.com',
    measurementId: 'G-4BT0CGGN94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQavu2-N_b7EHZe0Rx9Wa0RERC7-qNSc',
    appId: '1:824650774430:android:ad20b33abfb3496325488f',
    messagingSenderId: '824650774430',
    projectId: 'around-egypt-1cb7d',
    storageBucket: 'around-egypt-1cb7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCXCncGdGQ8aCDLdyuvZajIsQtSg2lGQ',
    appId: '1:824650774430:ios:554c86a06d17c30225488f',
    messagingSenderId: '824650774430',
    projectId: 'around-egypt-1cb7d',
    storageBucket: 'around-egypt-1cb7d.appspot.com',
    iosBundleId: 'com.example.aroundEgypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCXCncGdGQ8aCDLdyuvZajIsQtSg2lGQ',
    appId: '1:824650774430:ios:929f619032818d6625488f',
    messagingSenderId: '824650774430',
    projectId: 'around-egypt-1cb7d',
    storageBucket: 'around-egypt-1cb7d.appspot.com',
    iosBundleId: 'com.example.aroundEgypt.RunnerTests',
  );
}
